
== Background Information

[black]*Dick Anderson Construction*

Dick Anderson Construction is a general contractor/construction management company. 
They have been in business for more than 40 years.
They present by today’s commercial, civil, industrial, residential and energy projects. 
Their similar problems are that they have multiple programs within the company which causes 
missed steps and repeated work that’s not necessary. To resolve having multiple systems they 
started using 3-D modeling that spotted any conflicts and saved on costs.  
The solution was not in house but sourced out. It is a Vico software and contract BIM software. 
This approach is to increase coordination, quantity take off, reduce cost estimation,
project scheduling and production control. This change took them a year to implement with costs over 10,000.

[black]*Cognizant Technology Solutions*

Cognizant Digital Business works to reshape business models, modernize products and enhance customer 
experiences to drive growth. Cognizant Digital Operations reinvent and manage your most essential 
business processes with innovative ways of working. Cognizant Digital Systems and Technology Simplifying,
modernizing and securing the IT infrastructure and applications that are the backbone of your business. 
Thus, the main system in the company is communication through email. The organization provides 
collaborative solutions to their business and IT challenges with ideas that are discussed in detail
multiple times by their customers. More than 5,300 professionals around the world leverage deep 
industry knowledge across 15 verticals including: banking and financial services, healthcare, retail,
consumer goods and insurance to deliver digital solutions in key areas of client growth. 
All services are digital. Testing was an ongoing problem if a client did not have any testers 
due to the multiple different technology solutions it resulted in incorrect gap and requirements
which would create issues for the system. They hired a Quality Engineering and Assurance team to 
complete any testing if needed to provide any assurance needed. They also hired a team that is 
proficient and current in Java. The company hired approximately 10 Java experts.  
There are projects where Digital does not meet the requirements of what a client wants, therefore, 
resulting in a proposal not going live and not meeting the business plan. The company then decided 
to send more employees to locations and having face-to-face sessions.  This change that Cognizant 
had to make which costs more money however, it is what makes Great West Engineering successful for
 so many years. These changes were all inhouse and cost up to $400,000 per year extra. 

