== Business Description

{gweshort} opened its doors in 1985, starting with just two people
and expanded into two states and over 70 people. With branches in Helena,
Billings, and Boise as well as satellite offices in Bozeman, Missoula, 
and Malta.  Their expertise has expanded throughout the West. For over 30 
years {gweshort} has provided a broad range of engineering services to 
communities all over Montana and its surrounding states. Their broad range
of capabilities and depth of professional experience has allowed them to help
their clients and communities thrive and flourish.

{gweshort} core service areas include, but are not limited to:

* Professional water/wastewater
* Transportation construction
* Solid waste management 
* General construction management
* General development engineering
* Scientific surveying
* Environmental resource
* Grant writing and administration

{gweshort} has developed many enduring client relationships over 
the years to solve a expansive array of project challenges. 
They are proud of these long-term relationships, as it shows that {gweshort}
has a great commitment in providing the highest quality services to their 
clients. This gives their clients the confidence they need to pursue the changes 
that will better their community, and know it will be done within the budget
and on schedule.