== Executive Summary 

For this project, our group worked with {gwelong} ({gwe}), an engineering company
in Helena, Montana. {gwe} develops strong partnerships to provide scientific,
technical, and creative solutions to complex projects.

The needs of {gweshort} begin with a desktop application used for contract
management. Data extraction, input validation, and reporting present a number of
unique challenges. The current data store is not consistent with traditional
Relational Database Management Systems (<<rdbms,RDBMS>>), nor is <<vb.net,VB.Net>>
the optimum selection for enterprise level applications. According to
<<ieee,IEEE Spectrum>>, languages such as <<python,Python>>, <<java,Java>>,
and <<csharp,{CSHARP}>> rank within the {ieee-rank} of all programming languages
for enterprise and web application development.

Restructuring the current data store into a proper <<rdbms,RDBMS>> will aid in
resolving data extraction and reporting, but not without further development on
the interface. Implementing a modern interface that includes reporting will 
exceed current needs, and allow for easy expansion as the business grows.

The analysis team will provide {gweshort} with a recommended proposal and two
alternatives. Our findings are based on the latest technologies available,
and proven enterprise software stack implementations.

