[glossary]
== Glossary

The glossary is intended to help in understanding terms used throughout
the System Analysis and Design research. Terms are expressed in common industry
language and lean toward technology as their basis. Where feasible, sources are
provided with accompanying reference web-links.

[glossary]
[[dot.net,.NET]].NET::
The .NET Framework is a technology that supports building and running the next
generation of apps and XML Web services.
*Source*: https://docs.microsoft.com/en-us/dotnet/framework/get-started/overview[docs.microsoft.com]

[[adhoc,Ad-Hoc]]Ad-Hoc::
Ad hoc is a Latin phrase meaning "for this". In English, it generally signifies
a solution designed for a specific problem or task, non-generalizable, and not
intended to be able to be adapted to other purposes (compare with a priori).

[[ajera,Ajera]]Ajera::
Ajera contains scores of other features designed to provide strong A&E accounting
software in a streamlined manner. Recurring invoices and journal entries,
prepayments and finance charges can be easily setup.
*Source*: http://www.axium.com/products/ae-specific-accounting.aspx[axium.com]

[[csharp,CSHARP]]{CSHARP}::
{CSHARP} is an elegant and type-safe object-oriented language that enables developers
to build a variety of secure and robust applications that run on the .NET Framework.
You can use {CSHARP} to create Windows client applications, XML Web services,
distributed components, client-server applications, database applications,
and much, much more.
*Source*: https://docs.microsoft.com/en-us/dotnet/csharp/getting-started/introduction-to-the-csharp-language-and-the-net-framework[docs.microsoft.com]

[[cpp,CPP]]{CPP}::
{cpp} is a programming language. It literally means "increased C",
reflecting its nature as an evolution of the C language.
*Source*: http://www.cplusplus.com/info/faq/[cplusplus.com]

[[cba,CBA]]CBA::
A cost-benefit analysis is a process by which business decisions are analyzed.
The benefits of a given situation or business-related action are summed, and
then the costs associated with taking that action are subtracted. 
*Source*: https://www.investopedia.com/terms/c/cost-benefitanalysis.asp[invesopedia.com]

[[crm,CRM]]CRM::
Customer relationship management (CRM) is an approach to managing a company\'s
interaction with current and potential customers. It uses data analysis about
customers' history with a company and to improve business relationships with
customers, specifically focusing on customer retention and ultimately driving
sales growth.
*Source*: https://en.wikipedia.org/wiki/Customer_relationship_management[wikipedia.org]

[[csv,CSV]]CSV::
In computing, a comma-separated values (CSV) file stores tabular data (numbers
and text) in plain text. Each line of the file is a data record. Each record
consists of one or more fields, separated by commas. The use of the comma as a
field separator is the source of the name for this file format.
*Source*: https://en.wikipedia.org/wiki/Comma-separated_values[wikipedia.org]

[[crud,CRUD]]CRUD::
In computer programming, create, read, update, and delete (as an acronym CRUD)
are the four basic functions of persistent storage. Alternate words are
sometimes used when defining the four basic functions of CRUD, such as retrieve
instead of read, modify instead of update, or destroy instead of delete.
*Source*: https://en.wikipedia.org/wiki/Create,_read,_update_and_delete[wikipedia.org]

[[normalization, database normalization]] database normalization::
Normalization is the process of organizing data in a database. This includes 
creating tables and establishing relationships between those tables according 
to rules designed both to protect the data and to make the database more flexible 
by eliminating redundancy and inconsistent dependency.
*Source*: https://support.microsoft.com/en-us/help/283878/description-of-the-database-normalization-basics[support.microsoft.com]


[[edm,EDM]]EDM::
The Entity Data Model (EDM) is a set of concepts that describe the structure of
data, regardless of its stored form. The EDM borrows from the Entity-Relationship
Model described by Peter Chen in 1976, but it also builds on the Entity-Relationship
Model and extends its traditional uses.
*Source*: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/entity-data-model[docs.microsoft.com]

[[ef6,Entity FrameWork]]Entity Framework::
The Entity Framework is a set of technologies in ADO.NET that support the
development of data-oriented software applications.
*Source*: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/ef/overview[docs.microsoft.com]

[[fasb,FSAB]]FASB::
The FASB is recognized by the Securities and Exchange Commission as the
designated accounting standard setter for public companies.
*Source*: http://www.fasb.org/facts/[fasb.org]

[[gaap,GAAP]]GAAP::
Generally accepted accounting principles, or GAAP, are a set of rules that
encompass the details, complexities, and legalities of business and corporate
accounting. The Financial Accounting Standards Board (<<fasb,FASB>>) uses GAAP as the
foundation for its comprehensive set of approved accounting methods and
practices.
*Source*: http://www.accounting.com/resources/gaap/[accounting.com]

[[goldminecrm,GoldMineCRM]]GoldMineCRM::
Goldmine is a customer relationship management (CRM) system software package
produced by Frontrange Solutions.
*Source*: https://www.techopedia.com/definition/26958/goldmine[techopedia.com]

[[ieee,IEEE]]IEEE Spectrum::
IEEE Spectrum is the flagship magazine and website of the IEEE, the world’s
largest professional organization devoted to engineering and the applied sciences.
Our charter is to keep over 400,000 members informed about major trends and
developments in technology, engineering, and science.
*Source*: https://spectrum.ieee.org/static/aboutus[IEEE Spectrum]

[[ide,IDE]]IDE::
An Integrated Development Environment (IDE) is a software application that
provides comprehensive facilities to computer programmers for software development.
*Source*: https://en.wikipedia.org/wiki/Integrated_development_environment[wikipedia.org]

[[intranet,Intranet]]Intranet::
Microsoft® Windows® Small Business Server provides a preconfigured internal
Web site (an intranet) based on Windows® SharePoint® Services. This turn-key
site is available from within the company network at http://companyweb/. It
enables domain users to share information, such as documents, photographs, and
upcoming events, from a central location.
*Source*: https://technet.microsoft.com/en-us/library/cc720040(v=ws.10).aspx[technet.microsoft.com]

[[it,IT]]IT::
Information Technology (IT) is the application of computers to store, study,
retrieve, transmit and manipulate data,[1] or information, often in the context
of a business or other enterprise.
*Source*: https://en.wikipedia.org/wiki/Information_technology[wikipedia.org]

[[java,Java]]Java::
Java is a programming language and computing platform first released by Sun
Microsystems in 1995. There are lots of applications and websites that will
not work unless you have Java installed, and more are created every day. Java
is fast, secure, and reliable. From laptops to datacenters, game consoles to
scientific supercomputers, cell phones to the Internet, Java is everywhere!
*Source*: https://www.java.com/en/download/faq/whatis_java.xml[java.com]

[[mvc,MVC]]MVC::
MVC is a standard design pattern that many developers are familiar with. Some
types of Web applications will benefit from the MVC framework.
*Source*: https://msdn.microsoft.com/en-us/library/dd381412(v=vs.108).aspx[msdn.microsoft.com]

[[monodev,Mono Development]]Mono Development::
MonoDevelop enables developers to quickly write desktop and web applications on
Linux, Windows and Mac OSX. It also makes it easy for developers to port .NET
applications created with Visual Studio to Linux and Mac OS X maintaining a
single code base for all platforms.
*Source*: http://www.monodevelop.com/[monodevelopment.com]

[[paser,PASER]]PASER::
The PASER scale is a 1-10 rating system for road pavement condition developed
by the University of Wisconsin-Madison Transportation Information Center.
PASER uses visual inspection to evaluate pavement surface conditions.
*Source*: https://en.wikipedia.org/wiki/Pavement_Surface_Evaluation_and_Rating[wikipedia.org]

[[perl,Perl]]Perl::
"Perl" is a family of languages, "Perl 6" is part of the family, but it is a
separate language which has its own development team. Its existence has no
significant impact on the continuing development of "Perl 5".
*Source*: https://www.perl.org/about.html[perl.org]

[[php,PHP]]PHP::
 PHP is mainly focused on server-side scripting, so you can do anything any
 other CGI program can do, such as collect form data, generate dynamic page
 content, or send and receive cookies. But PHP can do much more.
 *Source*: http://php.net/manual/en/intro-whatcando.php[php.net]

[[python,Python]]Python::
Python is an interpreted, object-oriented, high-level programming language with
dynamic semantics.
*Source*: https://www.python.org/doc/essays/blurb/[python.org]

[[rdbms,RDBMS]]RDBMS::
A database is a means of storing information in such a way that information can
be retrieved from it. In simplest terms, a relational database is one that
presents information in tables with rows and columns. A Database Management
System (DBMS) handles the way data is stored, maintained, and retrieved. In the
case of a relational database, a Relational Database Management System (RDBMS)
performs these tasks.
*Source*: https://docs.oracle.com/javase/tutorial/jdbc/overview/database.html[docs.oracle.com]

[[rfq,RFQ]]RFQ::
A Request For Quote (RFQ) is a type of procurement solicitation in which a
company asks outside vendors to offer a quote for the completion of a
specific task or project.
*Source*: https://www.investopedia.com/terms/r/request-for-quote.asp[investopedia.com]

[[rot,ROI]]ROI::
Return Of Investment (ROI) is a performance measure used to evaluate the efficiency of an investment or to
compare the efficiency of a number of different investments. ROI measures the
amount of return on an investment relative to the investment’s cost.
*Source*: https://www.investopedia.com/terms/r/returnoninvestment.asp[[investopedia.com]

[[ruby,Ruby]]Ruby::
A dynamic, open source programming language with a focus on simplicity and
productivity. It has an elegant syntax that is natural to read and easy to write.
*Source*: https://www.ruby-lang.org/en/[ruby-lang.org]

[[sa,SA]]SA::
System Analysis (SA) is the act, process, or profession of studying an activity (such
as a procedure, a business, or a physiological function) typically by
mathematical means in order to define its goals or purposes and to discover
operations and procedures for accomplishing them most efficiently.
*Source*: https://www.merriam-webster.com/dictionary/systems%20analysis[merriam-webster.com]

[[tsep,TSEP]]TSEP::
The Montana Treasure Statement Endowment Program (TSEP) is a state-funded program
that is designed to help address the "affordability" of local infrastructure
projects by providing grants to lower the cost of constructing public facilities.
*Source*: http://comdev.mt.gov/programs/TSEP[comdev.mt.gov]

[[webapi,Web API]]Web API::
ASP.NET Web API is a framework that makes it easy to build HTTP services that
reach a broad range of clients, including browsers and mobile devices.
*Source*: https://msdn.microsoft.com/en-us/library/hh833994(v=vs.108).aspx[docs.microsoft.com]

[[usfs,USFS]]USFS::
United States Forest Service (USFS) is a multi-faceted agency that manages and protects 154 national forests
and 20 grasslands in 43 states and Puerto Rico. The agency’s mission is to
sustain the health, diversity, and productivity of the nation’s forests and
grasslands to meet the needs of present and future generations.
*Source*: https://www.fs.fed.us/about-agency[fs.fed.us]

[[studio,Visual Studio]]Visual Studio::
Fully-featured integrated development environment (<<ide,IDE>>) for Android, iOS,
Windows, web, and cloud.
*Source*: https://www.visualstudio.com/vs/[code.visualstudio.com]

[[vb.net,VB.NET]]VB.Net::
Visual Basic is engineered for productively building type-safe and
object-oriented applications.
*Source*: https://docs.microsoft.com/en-us/dotnet/visual-basic/[docs.microsoft.com]

[[vscore,VS Core]]VS Core::
DOT.Net Core gives you a blazing fast and modular platform for creating server
applications that run on Windows, Linux and Mac. Use Visual Studio Code with the
{csharp} extension to get a powerful editing experience with full support for
{csharp} IntelliSense (smart code completion) and debugging.
*Source*: https://code.visualstudio.com/docs/other/dotnet[code.visualstudio.com]

[[vpn,VPN]]VPN::
A Virtual Private Network (VPN) extends a corporate network through encrypted connections made over the
Internet. Because the traffic is encrypted between the device and the network,
traffic remains private as it travels.
*Source*: https://www.cisco.com/c/en/us/products/security/vpn-endpoint-security-clients/what-is-vpn.html[cisco.com]

[[webserver,Web Server]]Web Server::
The primary function of a web server is to store, process and deliver web pages
to clients. The communication between client and server takes place using the
Hypertext Transfer Protocol (HTTP).
*Source*: https://en.wikipedia.org/wiki/Web_server[wikipedia.org]
