== Needs Assessment

{gweshort} operates three primary business applications:

- <<goldminecrm,GoldmineCRM>> for Marketing, sales forecasting, and opportunity management
- <<ajera,Ajera>> Cost Accounting and Payroll Software
- Custom Contracts Management Application

The three systems are using {mssqlshort} for their data model.
However, they operate in isolation. Moving from a potential client, through to
final cost accounting, revenue recognition, and margin analysis is a manual
process. Our task was to assist in resolving several aspects of
their contract management workflow, primarily in the area of reporting

:numbered!:

[[needs-business-logic]]
=== Business Logic
* Provide a viable solution for their outdated database application
* Design a Relational Data Model (<<rdm,RDM>>) that can leverage the capabilities
of their existing accounting package implementation
* Provide a means to dynamically generate reports, either from further development 
of the in-house contracts management application, or through other potential applications.
* Provide low maintenance solutions for limited <<it,IT>> support staff

[[needs-application-interface]]
=== Application Interface
* Migration from a desktop application, to a Web Application Programming
Interface (<<webapi,Web API>>) would enable access from any number of devices:
desktop, tablet, and portable phones
* Rolling out changes to a signal point rather than many instances, saves time,
improves end-user satisfaction, and overall application maintenance costs.
* Several open sources, or free Framework <<ide,IDEs>> are available to support
the application design: (<<studio,Visual Studio>>), (<<vscore,VS Core>>), and
(<<monodev,Mono Development>>) could be employed with little to no cost to {gweshort}.
* As {gweshort} already employs {mssqlshort}, updating the data model
to match current industry standards could be done with modest effort.

[[needs-data-warehouse]]
=== Data Warehouse

The current data model is a non-normalized database composed of seven tables.
Moving the data structure through (<<normalization,database normalization>>) would provide several benefits:

* Ease of maintenance
* Eliminates duplicate entries
* Reduced data storage footprint
* Better security
* Caters for future expansion
* Allows for complex data queries
* Provides a better entry point for cross application data sharing
* Improves the Create, Review, Update, and Delete (<<crud,CRUD>>) process


=== Accounting

Allowing read access to the <<ajera,Ajera>> accounting
system will provide a number of additional benefits:

* Can enforce that a client exists in the accounting system before a 
contract can be created for that client.
* Ensures accuracy accross the accounting system and the contracts management system.
* Using a single set of account naming conventions will aid in preventing
business process confusion regarding cost accounting.

=== Report Generation
:numbered:
// TO-DO: Do we need to use the word "Currently"
// TO-DO: Is "comma-separated value files" the right phrase to use here?
Currently, contract reporting statistics is a manual process using Excel, and
comma-separated value files (<<csv,CSV>>). Providing a reporting interface to
the {mssqlshort} data model would allow any number of reports to be generated
on-demand, or, through a series static pre-written reports. Benefits of such an
implementation would be:

* Access to reporting by all end-users
* Standardized weekly, monthly, and yearly reporting
* Increased management, and administration efficiency
* Improved accuracy
* Cross-checking financial statements with trend analysis
* Assist in bringing reporting efforts closer to Generally Accepted
Accounting Practice (<<gaap,GAAP>>) standards