== Proposal Objectives

The overall objective, as requested by {gweshort}, is to provide reporting
functionality for their contracts management system; be that current, or a newly
implemented design. As with most system analysis and design objectives, the
overriding structure of the project can be characterized by four primary areas.
First, the contract management system must satisfy the informational requirements
needed to process and implement each contract. Second, the operational method
must align with the company\'s current workflow. Third, the solution must
satisfy management requirements in regards to implementation, and ease of
maintenance. Finally, the group will provide a <<cba,CBA>> that
outlines the current cost model in contrast to our proposal(s).

.[black]*Informational*
The analysis conclusion is to replace the current VB.NET desktop-application
with that of a modern web user interface backed by a relational
database model. Doing so provides inner-application access to data, transparency
in terms of contract workflow, and enables dynamic reporting capabilities.

.[black]*Operational*
Data, as a property of information, should be well organized, accessible,
and efficient in terms of access. Utilizing the company\'s current {mssqlshort}
implementation, (<<normalization,normalizing>>) the current data model, and
restructuring access will position the new implementation inline with operational
needs.

.[black]*Management*
Allowing read access to <<ajera,Ajera>> Accounting Software will ensure future
expansions of the Contract Management System will stay in-step with Generally
Accepted Accounting Practice (<<gaap,GAAP>>) and Finance and Accounting Policy
(<<fasb,FASB>>) reporting requirements. In doing so, implementation costs can
be kept to a minimum as the overall data structure is brownfield, thus requiring
minimal research to implement the solution. Likewise, sustaining costs are kept
low due to the fact each business system, as an independent object, provides an
element of overlap if future application consolidation is deemed appropriate.

.[black]*Cost Benefit Analysis*
A <<cba,CBA>> will accompany the recommended proposal and alternates provided.
Costs will be derived from current privately contracted developers of the region.
The benefit portion of the <<cba,CBA>> will take into account the individual time saved, 
and savings from the maintenance costs tied to the contract management application. 

In summary, the proposal will provide {gweshort} with three alternatives from
which to choose. Accompanying the proposal will be a primary recommendation,
and two alternates. Each option will provide a summary, short <<cba,CBA>>,
technical brief, sustaining engineering discussion, and conclusion by way of
pro\'s and con\'s.