== Second Alternative
Our primary and first alternative proposals provide {gweshort} with several
choices in resolving the needs of their current Contract Management System. Our 
final alternative will not add additional technology. Rather, provide a means
in which to significantly reduce implementation costs, provide a value added
service to Helena College Students, and map out an update schedule that suits
the operational tempo of {gweshort}.

In order to graduate, the Helena College Computer Technology (CT) program
requires students to work on an approved Capstone project, attend an Internship,
or participate in an approved Independent study program. All three activities are
supervised by Helena College CT Professors, and in most cases, backed by
professionals in the target industry.

The CT program requirements present a unique opportunity for {gweshort}. In short,
our final proposal recommends a collaboration between {gweshort} and Helena
College CT program participants.

// turn numbering off for inner sections
:numbered!:

=== Objective
The primary objective for the Great West Helena College Collaboration (GWHCC) is
to aid in solving the <<it,IT>> challenges {gweshort} face, while providing great
benefit to the students whom assist in it's tasking. While current system analysis
is focused on {gweshort}'s Contract Management System, it should be understood
that such collaboration could extend well past the current proposals.

=== Benefits
{gweshort} retains the services of software development companies to perform
periodic maintenance. Normally, such activity occurs only a few times per year.
This update regiment is well suited to the fall / spring semester cycles at
Helena College. Each semester provides a number of programming and networking
students that could assist {gweshort} with their <<it,IT>> needs.

.[black]*Key Benefits for Great West Engineering*
* Significant costs saving can be realized through Capstone activity. For the
most part, there is little to no cost for the host company.

* Often times, Capstones and Internships are classed as charitable contributions,
thus providing the host company with some level tax relief.

* Local resourcing allows for tighter integration between the host company
and service provider, thus improving product performance and customer
satisfaction.

* Consistent leadership from Helena College professors ensures key milestones
remain in focus, and continuity overlaps the fall / spring scholastic schedules.

* Host companies receive an objective analysis of critical issues, not only for 
the current project, but could expand to additional {gweshort} needs.

* Establishes connection to the Helena College faculty and students for future
project collaboration.

.[black]*Key Benefits for Helena College Students*
* Integration and synthesise of acquired skills in a real-world environments.

* Students are encouraged to become professional, and adaptive to a wider range
of conditions than experienced at the university level.

* Allows students to showcase their skills, build reference networks, and
link to potential employers. Such links can be with the host company, or through
mutual partnership connections.

* Aids in the transition from student to workforce.

* Allows students to evaluate companies as possible career choices.

=== Cost Analysis
Unlike our primary and first alternative proposals, opting for the GWHCC
solution will provide significant cost savings to {gweshort}. Removing the
yearly maintenance fee of nearly $10,000 dollars all but ensures immediate
Return On Investment (<<roi,ROI>>). Partnering with Helena College also negates
the need to purchase new or updated Framework IDE's needed for application
compiling and distribution to <<webserver,Web Servers>>.

Bringing the solution in-house creates a number of database selection options. 
While somewhat minor as compared to maintenance fee and framework costs, moving
the contracts database off of {mssql} will further reduce licensing fees. More
importantly, doing so ensures the overall cost of implementation remains at
near-zero values for the Contracts Management System.

In summary, the GWHCC proposal has the potential to bring application development,
deployment, and maintenance costs to near-zero values. Considering all benefits
leads to but one conclusion; a collaborative effort is a Win/Win for all
involved.

// do not take this out
:numbered: